### ISSUE TITLE
Build on  ppc64le architecture failed lack of immintrin.h

### ISSUE THREAD

**Issue by machelcheng** [intel/isa-l_crypto#20] opened 2019-06-28 03:45 UTC
make --no-print-directory all-am
  CC       md5_mb/md5_ctx_sse.lo
In file included from ./include/memcpy_inline.h:40:0,
                 from md5_mb/md5_ctx_sse.c:31:
./include/intrinreg.h:55:3: error: #error "The compiler must be configured to optimize for speed and support at least SSE instructions."  # error "The compiler must be configured to optimize for speed and support at least SSE instructions."
   ^~~~~
./include/intrinreg.h:56:3: error: #error "Please specify the following gcc flags: -O3 [-mavx]"   # error "Please specify the following gcc flags: -O3 [-mavx]"
   ^~~~~
./include/intrinreg.h:66:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:2553: recipe for target 'md5_mb/md5_ctx_sse.lo' failed
make[1]: *** [md5_mb/md5_ctx_sse.lo] Error 1
Makefile:1623: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by machelcheng** [comment] 2019-06-28 03:47
Anyone can tell me how to solve this compile error? I'll be very grateful.

**Comment by machelcheng** [comment] 2019-06-28 04:00
I compile with following  steps:
./autogen.sh
./configure
make
sudo make install

And in third step: “make”， found the error

**Comment by gbtucker** [comment] 2019-06-29 00:21
Can you include the output from ./configure?  It shouldn't be building the sse versions on ppc.

**Comment by machelcheng** [comment] 2019-07-01 02:40
# ./autogen.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:23: installing 'build-aux/compile'
configure.ac:12: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'

----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------

./configure --prefix=/usr --libdir=/usr/lib


# ./configure --prefix=/usr --libdir=/usr/lib
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for style of include used by make... 
GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking build system type... powerpc64le-unknown-linux-gnu
checking host system type... powerpc64le-unknown-linux-gnu
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert powerpc64le-unknown-linux-gnu file names to powerpc64le-unknown-linux-gnu format... func_convert_file_noop
checking how to convert powerpc64le-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for yasm... yes
checking for modern yasm... yes
checking for optional yasm AVX512 support... no
checking for optional yasm SHA-NI support... no
checking for nasm... yes
checking for modern nasm... yes
checking for optional nasm AVX512 support... yes
checking for optional nasm SHA-NI support... yes
Using assembler nasm
Using yasm args target "linux" "-f elf64"
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for inline... inline
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for memmove... yes
checking for memset... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libisal_crypto.pc
config.status: executing depfiles commands
config.status: executing libtool commands

        isa-l_crypto 2.21.0
        =====

        prefix:                 /usr
        sysconfdir:             ${prefix}/etc
        libdir:                 /usr/lib
        includedir:             ${prefix}/include

        compiler:               gcc
        cflags:                 -g -O2
        ldflags:                

        debug:                  no

**Comment by machelcheng** [comment] 2019-07-01 02:41
You mean is not support ppc architecture？

**Comment by machelcheng** [comment] 2019-07-01 02:42
You mean is not support ppc architecture？ @

**Comment by machelcheng** [comment] 2019-07-01 02:42
You mean is not support ppc architecture？
@gbtucker

**Comment by haoyu01** [comment] 2019-07-01 06:16
@machelcheng  , 

multiarch is verified on aarch64 platform . 

And I could not reproduce this issue . I verified it with qemu-ppc64le ubuntu 18.04 .
I got the error message in issue21

**Comment by machelcheng** [comment] 2019-07-01 06:24
@haoyu01 ，
Yes，I build this program in qemu-ppc64le ubuntu 18.04. this program is supported by intel x86 architechture. 
I can not compile successful in ppc, you can use branch isa-l_crypto-2.21.0， and then you will get this error message(fatal error: immintrin.h: No such file or directory)

**Comment by haoyu01** [comment] 2019-07-01 07:31
@machelcheng 
 isa-l_crypto-2.21.0 does not support multi-arch . 
And multi-arch is added after https://github.com/intel/isa-l_crypto/commit/ffd20d8c8ff2f2ef0a5885b6d47bbbcf1ab393d3

**Comment by haoyu01** [comment] 2019-07-01 07:33
I think this issue has been fixed after https://github.com/intel/isa-l_crypto/commit/ffd20d8c8ff2f2ef0a5885b6d47bbbcf1ab393d3 .

@gbtucker and @machelcheng  , I thnk we can close this issue .

**Comment by machelcheng** [comment] 2019-07-01 07:39
If the issue 21 has been fixed and can build passed on ppc64le platform, i think this issue can close.
thank you!

**Comment by gbtucker** [comment] 2019-07-01 22:04
OK, we will close as specifically the `immintrin.h` was fixed and we will follow up on base function problem in other issue.

**Closed by gbtucker** 2019-07-01 22:04 UTC
