### ISSUE TITLE
SHA512 hash is broken in aarch64

### ISSUE THREAD

**Issue by leiless** [intel/isa-l_crypto#87] opened 2021-11-19 07:46 UTC
@gbtucker, As I tested, the SHA512 hash is not working properly in Linux aarch64.

The hash result for input string `abc` I got is always an empty hash value (i.e. `printf '' | shasum -a512`):
`cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`

But the expected SHA512 hash value for `abc` is `ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f`

The sample code can be found at: https://gist.github.com/leiless/e077a8d42f0c7fbfa23ff31d6cbcf078
In the `isal_crypto_submit_flush.cpp`, I try to calculate the SHA512 hash value of the string `abc`
```c
    (void) submit_flush(mgr, &ctx, "a", 1, HASH_FIRST);
    (void) submit_flush(mgr, &ctx, "b", 1, HASH_UPDATE);
    (void) submit_flush(mgr, &ctx, "c", 1, HASH_UPDATE);
    (void) submit_flush(mgr, &ctx, nullptr, 0, HASH_LAST);
    assert(ctx.error == HASH_CTX_ERROR_NONE);
    print_hash(&ctx, false);
```
~~I don't know if I missed/misused anything, but it works fine in x86_64 machines.~~

Based on `HEAD` commit `a6dc869666fca3eef9a0305b290e4e0fc8bac645`

**Comment by gbtucker** [comment] 2021-11-23 00:06
This sample code passes the cross compiler.  Not sure what is different on HW.
```
$ aarch64-linux-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static  -o tst && ./tst
ISA-L crypto version: 2.24.0
ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
$ file tst
tst: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 4.14.0, with debug_info, not stripped

```

**Comment by leiless** [comment] 2021-11-23 01:57
I use the cross compiler in Linux aarch64, still the wrong hash value.

```
$ aarch64-linux-gnu-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static -Wno-format && ./a.out
ISA-L crypto version: 2.24.0
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

$ file a.out
a.out: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=a5965bf909a888feae182673fb0fc98ba94146ab, for GNU/Linux 3.7.0, with debug_info, not stripped

$ uname -a
Linux nanopi-r4s 5.10.73-rockchip64 #trunk SMP PREEMPT Sat Oct 16 02:00:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by leiless** [comment] 2021-11-23 01:59
Both of my two aarch64 machines are Ubuntu distro

**Comment by fengchunsong** [comment] 2022-05-26 04:52
In sha512_update, if the transferred len is not enough for SHA512_BLOCK_SIZE, the data needs to be copied to partial_block_buffer. Do you have a fix? If not, I'll send a patch to fix it.

**Comment by leiless** [comment] 2022-05-26 06:02
> Do you have a fix? If not, I'll send a patch to fix it.

You're welcome!

**Comment by fengchunsong** [comment] 2022-05-27 02:52
fix this issue in https://github.com/intel/isa-l_crypto/pull/94

**Comment by leiless** [comment] 2022-05-27 03:11
Oh, it's obvious that the SHA512 hash value `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e` is the hash value of the empty string.

```
$ echo -n | shasum -a512
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e  -
```

**Comment by fengchunsong** [comment] 2022-05-27 03:27
Yes, using your test program, the test results are consistent with the shasum command.

**Comment by fengchunsong** [comment] 2022-05-27 03:29
I found this problem when I was running the daos test.
https://daosio.atlassian.net/browse/DAOS-10646?filter=-2

**Comment by yuhaoth** [comment] 2022-06-02 03:09
@leiless , in your platforms, it trigger base functions.  A72 does not support `sha512*` instructions . It should call base function.

**Comment by fengchunsong** [comment] 2022-06-02 03:14
Yes, it calls the base function, I fixed the issue where base does not support less than 128 bytes, and aarch64 has no problem.Could you help to review?

**Comment by yuhaoth** [comment] 2022-06-02 06:25
Sure. I got your review request. I am try reproduce this issue.

**Comment by yuhaoth** [comment] 2022-06-02 06:58
I could not reproduce the issue.
```
haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ printf '' | shasum -a512
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e  -
haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ aarch64-linux-gnu-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static -Wno-format && ./a.out
ISA-L crypto version: 2.24.0
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ lscpu
Architecture:        aarch64
CPU op-mode(s):      64-bit
Byte Order:          Little Endian
CPU(s):              224
On-line CPU(s) list: 0-223
Thread(s) per core:  4
Core(s) per socket:  28
Socket(s):           2
NUMA node(s):        2
Vendor ID:           Cavium
Model:               0
Model name:          ThunderX2 99xx
Stepping:            0x1
CPU max MHz:         2500.0000
CPU min MHz:         1000.0000
BogoMIPS:            400.00
L1d cache:           1.8 MiB
L1i cache:           1.8 MiB
L2 cache:            14 MiB
L3 cache:            64 MiB
NUMA node0 CPU(s):   0-111
NUMA node1 CPU(s):   112-223
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
```

**Comment by yuhaoth** [comment] 2022-06-02 06:59
> I use the cross compiler in Linux aarch64, still the wrong hash value.
> 
> ```
> $ aarch64-linux-gnu-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static -Wno-format && ./a.out
> ISA-L crypto version: 2.24.0
> cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
> 
> $ file a.out
> a.out: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=a5965bf909a888feae182673fb0fc98ba94146ab, for GNU/Linux 3.7.0, with debug_info, not stripped
> 
> $ uname -a
> Linux nanopi-r4s 5.10.73-rockchip64 #trunk SMP PREEMPT Sat Oct 16 02:00:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
> $ uname -a
> Linux raspi-4b 5.13.0-1010-raspi #12-Ubuntu SMP PREEMPT Tue Nov 9 15:30:22 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
> ```

@leiless  the hash value is correct.

**Comment by yuhaoth** [comment] 2022-06-02 06:59
> This sample code passes the cross compiler. Not sure what is different on HW.
> 
> ```
> $ aarch64-linux-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static  -o tst && ./tst
> ISA-L crypto version: 2.24.0
> ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
> $ file tst
> tst: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 4.14.0, with debug_info, not stripped
> ```

Could you share `lscpu` output?

**Comment by leiless** [comment] 2022-06-02 07:13
> I could not reproduce the issue.
> 
> ```
> haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ printf '' | shasum -a512
> cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e  -
> haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ aarch64-linux-gnu-g++ isal_crypto_submit_flush.cpp -L prefix/lib -I prefix/include -lisal_crypto -static -Wno-format && ./a.out
> ISA-L crypto version: 2.24.0
> cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
> haoyu01@haoyu01-01-arm-vm:~/work/isa-l_crypto$ lscpu
> Architecture:        aarch64
> CPU op-mode(s):      64-bit
> Byte Order:          Little Endian
> CPU(s):              224
> On-line CPU(s) list: 0-223
> Thread(s) per core:  4
> Core(s) per socket:  28
> Socket(s):           2
> NUMA node(s):        2
> Vendor ID:           Cavium
> Model:               0
> Model name:          ThunderX2 99xx
> Stepping:            0x1
> CPU max MHz:         2500.0000
> CPU min MHz:         1000.0000
> BogoMIPS:            400.00
> L1d cache:           1.8 MiB
> L1i cache:           1.8 MiB
> L2 cache:            14 MiB
> L3 cache:            64 MiB
> NUMA node0 CPU(s):   0-111
> NUMA node1 CPU(s):   112-223
> Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
> ```

Hi, @yuhaoth, you just reproduced it.
The `isal_crypto_submit_flush.cpp` print the empty SHA512 hash, i.e. `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`.

But the expected hash value is
```
$ printf abc | shasum -a 512
ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f  -
```

**Comment by yuhaoth** [comment] 2022-06-02 07:16
@leiless I misunderstand it . 
Could you update the description of this issue?

**Comment by leiless** [comment] 2022-06-02 07:20
> @leiless I misunderstand it . Could you update the description of this issue?

https://github.com/intel/isa-l_crypto/issues/87#issue-1058241706, please kindly read it again.

**Comment by yuhaoth** [comment] 2022-06-02 07:28
> > @leiless I misunderstand it . Could you update the description of this issue?
> 
> [#87 (comment)](https://github.com/intel/isa-l_crypto/issues/87#issue-1058241706), please kindly read it again.

Reproduced . It is not only found in aarch64. I can reproduce it in x86 also.

**Comment by leiless** [comment] 2022-06-02 07:31
> > > @leiless I misunderstand it . Could you update the description of this issue?
> > 
> > 
> > [#87 (comment)](https://github.com/intel/isa-l_crypto/issues/87#issue-1058241706), please kindly read it again.
> 
> Reproduced . It is not only found in aarch64. I can reproduce it in x86 also.

By saying x86, do you mean x86_32 or x86_64?

The SHA512 hash value of `abc` in x86_64 is correct as I tested previously.
https://gist.github.com/leiless/e077a8d42f0c7fbfa23ff31d6cbcf078?permalink_comment_id=3967462#gistcomment-3967462

**Comment by yuhaoth** [comment] 2022-06-02 07:55
All platform can reproduce it with a special build. 

With below script, and replace `#include <isa-l_crypto.h>` with `#include <sha512_mb.h>` , remove version print .
```
make -f Makefile.unx clean
make -f Makefile.unx lib -j20 arch=noarch
g++ isal_crypto_submit_flush.cpp -Iinclude -static  -o tst bin/isa-l_crypto.a
printf abc | shasum -a512
```

**Comment by yuhaoth** [comment] 2022-06-02 08:27
@gbtucker , the issue is not only exist in SHA512 , it can be reproduce in SHA256 also.
below is my test code and test script. the code is based on @leiless 's code

https://gist.github.com/yuhaoth/54ab60a269218e710cf245e3dc620f9b
https://gist.github.com/yuhaoth/292629ae66b5a1c3d5293665e79e6cd2

**Comment by leiless** [comment] 2022-06-02 08:33
> @gbtucker , the issue is not only exist in SHA512 , it can be reproduce in SHA256 also. below is my test code and test script. the code is based on @leiless 's code
> 
> https://gist.github.com/yuhaoth/54ab60a269218e710cf245e3dc620f9b https://gist.github.com/yuhaoth/292629ae66b5a1c3d5293665e79e6cd2

Glad you just found another bug, hope you guys can fix it. I have no such background in cryptography.

**Comment by fengchunsong** [comment] 2022-06-02 08:56
> @gbtucker , the issue is not only exist in SHA512 , it can be reproduce in SHA256 also. below is my test code and test script. the code is based on @leiless 's code
> 
> https://gist.github.com/yuhaoth/54ab60a269218e710cf245e3dc620f9b https://gist.github.com/yuhaoth/292629ae66b5a1c3d5293665e79e6cd2

# g++ isal_crypto_submit_flush.cpp -Iinclude -static -DSHA512 -o tst bin/isa-l_crypto.a
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

**Comment by fengchunsong** [comment] 2022-06-02 09:00
> All platform can reproduce it with a special build.
> 
> With below script, and replace `#include <isa-l_crypto.h>` with `#include <sha512_mb.h>` , remove version print .
> 
> ```
> make -f Makefile.unx clean
> make -f Makefile.unx lib -j20 arch=noarch
> g++ isal_crypto_submit_flush.cpp -Iinclude -static  -o tst bin/isa-l_crypto.a
> printf abc | shasum -a512
> ```
When no arch is configured, will sha512_ctx_mgr_submit_base be invoked in the test?

**Comment by yuhaoth** [comment] 2022-06-02 09:25
yes, it will be called.

**Comment by fengchunsong** [comment] 2022-06-02 09:26
make -f Makefile.unx clean
make -f Makefile.unx lib -j20 arch=noarch
g++ isal_crypto_submit_flush.cpp -Iinclude -static  -o tst bin/isa-l_crypto.a

**Comment by fengchunsong** [comment] 2022-06-02 10:06
I know why, Base's Hash results returned in Submit, and Flush returned Null. So modifying the test program is OK.

> yes, it will be called.

I know why, Base's Hash results returned in Submit, and Flush returned Null. So modifying the test program is OK.

**Comment by fengchunsong** [comment] 2022-06-02 10:11
submit_flush(HASH_CTX_MGR *mgr, HASH_CTX *ctx, const void *buffer, uint32_t len, HASH_CTX_FLAG flags) {
    HASH_CTX *job = ctx_mgr_submit(mgr, ctx, buffer, len, flags);

    if (job != nullptr) {
        assert(job == ctx);

        assert(job->error == HASH_CTX_ERROR_NONE);

    }



   HASH_CTX *jobf  = ctx_mgr_flush(mgr);

    if (jobf != nullptr) {
        assert(jobf == ctx);

        assert(jobf->error == HASH_CTX_ERROR_NONE);
       return jobf;

    }

    return job;

}

This should pass in share512.

**Comment by fengchunsong** [comment] 2022-06-06 02:30
Use shared isa-l_crypto, the test can passed.
make -f Makefile.unx clean
make -f Makefile.unx slib -j20 arch=noarch
g++ isal_crypto_submit_flush.cpp -Iinclude -o tst -lisa-l_crypto -Lbin
printf abc | shasum -a512

**Comment by fengchunsong** [comment] 2022-06-06 02:55
Use static  isa-l_crypto, the test can passed with my patch. can you check whether you used my patch?
make -f Makefile.unx clean
make -f Makefile.unx lib -j20 arch=noarch
g++ isal_crypto_submit_flush.cpp -Iinclude  -DSHA512 -o tst  -lm -lc -lstdc++  bin/isa-l_crypto.a

**Closed** 2022-06-09 17:25 UTC
